### ISSUE TITLE
[Feature Request] The automatic downloads of Boxart and Icon appear to be inaccurate

### ISSUE THREAD

**Issue by DDXDB** [xenia-manager/xenia-manager#175]
When I add 465607F0 and 465607E7, the manager confused the two.
I got boxart for 465607F0 and title name for 465607F0, whether it's 465607F0 or 465607F0
It is recommended to learn AuroraAssetEditor to get assets from xbox.com and specify the store area to get them from.
https://github.com/XboxUnity/AuroraAssetEditor

**Comment by shazzaam7** [comment]
Please post logs from Xenia Manager. Use a service like [Pastebin](https://pastebin.com/) or [Github Gists](https://gist.github.com/)

**Comment by DDXDB** [comment]
[Log-20241020_002.txt](https://github.com/user-attachments/files/17451016/Log-20241020_002.txt)
I tested other games and it seemed like a big problem, 4B5607D4 was NINJA GAIDEN 3, and the manager mistakenly identified it as NINJA GAIDEN 3 Razor's Edge, but boxart was correct.

**Comment by shazzaam7** [comment]
I think I have fixed this now in the latest [dev build](https://github.com/xenia-manager/xenia-manager/releases/download/experimental/xenia_manager_experimental.zip). Let me know if it works.

**Comment by DDXDB** [comment]
@shazzaam7 
I have updated to 1.15.2

465607E7 is still incorrectly identified as 465607F0. And the 465607F0 icon is missing. This icon appears to exist only in the Japanese Marketplace.
